version: '3.9'

services:

  # NGINX IMAGE !
  nginx:
    image: nginx
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - "./docker/nginx/log:/var/log/nginx"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${PROJECT_PATH}:${CONTAINER_PROJECT_PATH}"
    depends_on:
      - php
    networks:
      - symfony-local

  # PHP IMAGE !
  php:
    image: php:8.1-fpm
    container_name: php-container
    build:
      context: "./docker/php"
    ports:
      - "8081:80"
    volumes:
      - "./docker/php/log:/usr/local/var/log"
      - "./docker/php/conf/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./docker/php/conf/my.ini:/usr/local/etc/php/conf.d/my.ini"
      - "${PROJECT_PATH}:${CONTAINER_PROJECT_PATH}"
    depends_on:
      - database
    networks:
      - symfony-local

  # POSTGRE IMAGE
  database:
    image: postgres
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      #- db-data:/var/lib/postgresql/data:rw
      - ./docker/psql:/var/lib/postgresql/data:rw
    networks:
      - symfony-local

volumes:
  db-data:

networks:
  symfony-local:
    driver: bridge